### ISSUE TITLE
Record video

### ISSUE THREAD

**Issue by meduar** [a1q123456/Harmonic#6]
I can see in the new release there is an option to record video, do you have an example or how could I record?

Thanks,

**Comment by a1q123456** [comment]
okay, i'll update docs soon

**Comment by a1q123456** [comment]
I've updated the docs

**Comment by bakamaru** [comment]
recording is not working. :(

**Comment by a1q123456** [comment]
> recording is not working. :(

Hi, thanks for your testing, can you provide a sample code, or exception call stack? so I can analyse the reason. 

BTW: you need to push video to url: rtmp://<ip_address>/record/<stream_name> to record video

**Comment by bakamaru** [comment]
ffmpeg -i rtmp://localhost/living/STREAM_NAME -c:v libx264 -preset medium -maxrate 3500k -bufsize 6000k -pix_fmt yuv420p -g 30 -c:a aac -b:a 160k -ac 2 -ar 44100 -f flv rtmp://localhost/record/STREAM_NAME 



`System.Net.Sockets.SocketException Message: An existing connection was forcibly closed by the remote host
System.Net.Sockets.SocketException Message: An established connection was aborted by the software in your host machine
System.Net.Sockets.SocketException Message: An existing connection was forcibly closed by the remote host
System.Net.Sockets.SocketException Message: An existing connection was forcibly closed by the remote host
System.Net.Sockets.SocketException Message: An existing connection was forcibly closed by the remote host
System.Net.Sockets.SocketException Message: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at Harmonic.Networking.Rtmp.IOPipeLine.Producer(Socket s, PipeWriter writer, CancellationToken ct) in D:\klive\Harmonic\Networking\Rtmp\IOPipeLine.cs:line 186
   at Harmonic.Hosting.RtmpServer.AcceptCallback(IAsyncResult ar, CancellationToken ct) in D:\klive\Harmonic\Hosting\RtmpServer.cs:line 116
   at Harmonic.Networking.Rtmp.IOPipeLine.Writer(CancellationToken ct) in D:\klive\Harmonic\Networking\Rtmp\IOPipeLine.cs:line 168
   at Harmonic.Hosting.RtmpServer.AcceptCallback(IAsyncResult ar, CancellationToken ct) in D:\klive\Harmonic\Hosting\RtmpServer.cs:line 116
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at Harmonic.Networking.Rtmp.IOPipeLine.Producer(Socket s, PipeWriter writer, CancellationToken ct) in D:\klive\Harmonic\Networking\Rtmp\IOPipeLine.cs:line 186
   at Harmonic.Hosting.RtmpServer.AcceptCallback(IAsyncResult ar, CancellationToken ct) in D:\klive\Harmonic\Hosting\RtmpServer.cs:line 116
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at Harmonic.Networking.Rtmp.IOPipeLine.Producer(Socket s, PipeWriter writer, CancellationToken ct) in D:\klive\Harmonic\Networking\Rtmp\IOPipeLine.cs:line 186
   at Harmonic.Hosting.RtmpServer.AcceptCallback(IAsyncResult ar, CancellationToken ct) in D:\klive\Harmonic\Hosting\RtmpServer.cs:line 116
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at Harmonic.Networking.Rtmp.IOPipeLine.Producer(Socket s, PipeWriter writer, CancellationToken ct) in D:\klive\Harmonic\Networking\Rtmp\IOPipeLine.cs:line 186
   at Harmonic.Hosting.RtmpServer.AcceptCallback(IAsyncResult ar, CancellationToken ct) in D:\klive\Harmonic\Hosting\RtmpServer.cs:line 116
   at Harmonic.Networking.Rtmp.IOPipeLine.Writer(CancellationToken ct) in D:\klive\Harmonic\Networking\Rtmp\IOPipeLine.cs:line 168
   at Harmonic.Hosting.RtmpServer.AcceptCallback(IAsyncResult ar, CancellationToken ct) in D:\klive\Harmonic\Hosting\RtmpServer.cs:line 116
System.Net.Sockets.SocketException Message: The I/O operation has been aborted because of either a thread exit or an application request
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at Harmonic.Networking.Rtmp.IOPipeLine.Producer(Socket s, PipeWriter writer, CancellationToken ct) in D:\klive\Harmonic\Networking\Rtmp\IOPipeLine.cs:line 186
   at Harmonic.Hosting.RtmpServer.AcceptCallback(IAsyncResult ar, CancellationToken ct) in D:\klive\Harmonic\Hosting\RtmpServer.cs:line 116
System.Net.Sockets.SocketException Message: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at Harmonic.Networking.Rtmp.IOPipeLine.Writer(CancellationToken ct) in D:\klive\Harmonic\Networking\Rtmp\IOPipeLine.cs:line 168
   at Harmonic.Hosting.RtmpServer.AcceptCallback(IAsyncResult ar, CancellationToken ct) in D:\klive\Harmonic\Hosting\RtmpServer.cs:line 116`

**Comment by bakamaru** [comment]
can you help out..
